backend:
  name: git-gateway
  branch: gallery

media_folder: static/img
public_folder: /img

collections:
  - name: 'trip'
    label: 'Reise'
    folder: 'src/pages/trip'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'trip-post',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: Bild, name: image, widget: image, required: false }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }

  - name: 'gallery'
    label: 'Gallery'
    folder: 'src/pages/gallery'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'gallery',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
      - {
          label: Hauptbild,
          name: mainImage,
          widget: object,
          fields:
            [
              { label: Bild, name: image, widget: image },
              { label: Text, name: text, widget: string },
            ],
        }
      - {
          label: 'Bilder',
          name: 'images',
          widget: 'list',
          fields:
            [
              { label: Bild, name: image, widget: image },
              { label: Text, name: text, widget: text },
            ],
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'Über'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Titel', name: 'title', widget: 'string' }
          - { label: 'Inhalt', name: 'body', widget: 'markdown' }

      - file: 'src/pages/index.md'
        label: 'Startseite'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Titel, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Bild, name: image, widget: image }
          - {
              label: Einführung,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Überschrift, name: heading, widget: string },
                  { label: Text, name: text, widget: text },
                  {
                    label: Bild,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Bild, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Blog,
              name: blog,
              widget: object,
              fields:
                [
                  { label: Überschrift, name: heading, widget: string },
                  { label: Text, name: text, widget: text },
                ],
            }
